---
kind: pipeline
type: docker
name: default

steps:
  - name: build-linux
    image: golang:1.13-buster
    commands:
      - make build BUILD_OUTPUT=wait4x-linux-amd64
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: build-linux-musl
    image: golang:1.13-alpine
    commands:
      - apk --update add make git
      - make build BUILD_OUTPUT=wait4x-linux-musl-amd64
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: build-darwin
    image: golang:1.13-buster
    commands:
      - make build BUILD_OUTPUT=wait4x-darwin-amd64
    environment:
      GOARCH: amd64
      GOOS: darwin

  - name: build-windows
    image: golang:1.13-buster
    commands:
      - make build BUILD_OUTPUT=wait4x-windows-amd64
    environment:
      GOARCH: amd64
      GOOS: windows

  - name: docker
    image: plugins/docker
    settings:
      repo: atkrad/wait4x
      auto_tag: true
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    depends_on:
      - build-linux-musl

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - wait4x-linux-amd64
        - wait4x-linux-musl-amd64
        - wait4x-darwin-amd64
        - wait4x-windows-amd64
      checksum:
        - sha256
    when:
      event:
        - tag
    depends_on:
      - build-linux
      - build-linux-musl
      - build-darwin
      - build-windows
