---
kind: pipeline
type: docker
name: build-linux

steps:
  - name: build
    image: golang:1.13-buster
    commands:
      - make build BUILD_OUTPUT=wait4x-linux-amd64
    environment:
      GOARCH: amd64
      GOOS: linux

---
kind: pipeline
type: docker
name: build-linux-musl

steps:
  - name: build
    image: golang:1.13-alpine
    commands:
      - apk --update add make git
      - make build BUILD_OUTPUT=wait4x-linux-musl-amd64
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: docker
    image: plugins/docker
    settings:
      repo: atkrad/wait4x
      auto_tag: true
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

---
kind: pipeline
type: docker
name: build-darwin

steps:
  - name: build
    image: golang:1.13-buster
    commands:
      - make build BUILD_OUTPUT=wait4x-darwin-amd64
    environment:
      GOARCH: amd64
      GOOS: darwin

---
kind: pipeline
type: docker
name: build-windows

steps:
  - name: build
    image: golang:1.13-buster
    commands:
      - make build BUILD_OUTPUT=wait4x-windows-amd64
    environment:
      GOARCH: amd64
      GOOS: windows

---
kind: pipeline
type: docker
name: release

steps:
  - name: github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - wait4x-linux-amd64
        - wait4x-linux-musl-amd64
        - wait4x-darwin-amd64
        - wait4x-windows-amd64
      checksum:
        - sha256
    when:
      event:
        - tag

depends_on:
  - build-linux
  - build-linux-musl
  - build-darwin
  - build-windows
